bug fix2

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -33,11 +33,11 @@ runs:
       # Sync files to bucket
       # echo "Syncing bucket $BUCKET ..."
     - run:  gsutil -m rsync -r -c -d -x ${{ inputs.rsync_exclude }} /github/workspace/${{ github.event.repository.name }} gs://${{ inputs.GCS_BUCKET }}/${{ github.event.repository.name }}
-            if [ $? -ne 0 ]; then
-            echo "Syncing failed"
-            exit 1
-            fi
-            echo "Done."
+          #  if [ $? -ne 0 ]; then
+          #  echo "Syncing failed"
+          #  exit 1
+          #  fi
+          # echo "Done."
       shell: bash
     - name: Slack Notification
       uses: rtCamp/action-slack-notify@v2
